<?php

/**
 * Jasny Social
 * World's best PHP library for webservice APIs
 *
 * @license http://www.jasny.net/mit MIT
 * @copyright 2012 Jasny
 */


namespace Jasny\ISO;

class CountryNativeNames
{
    /**
     * List of native names
     *
     * @var array
     */
    protected static $list = [
        "Ascension Island" => "AC",
        "Andorra" => "AD",
        "الإمارات العربية المتحدة" => "AE",
        "افغانستان" => "AF",
        "Antigua and Barbuda" => "AG",
        "Anguilla" => "AI",
        "Shqipëria" => "AL",
        "Հայաստան" => "AM",
        "Nederlandse Antillen" => "AN",
        "Angola" => "AO",
        "Antarctica" => "AQ",
        "Argentina" => "AR",
        "American Samoa" => "AS",
        "Amerika Sāmoa" => "AS",
        "Österreich" => "AT",
        "Öſterreich" => "AT",
        "Australia" => "AU",
        "Aruba" => "AW",
        "Åland" => "AX",
        "Azərbaycan" => "AZ",
        "Азәрбајҹан" => "AZ",
        "Bosna i Hercegovina" => "BA",
        "Босна и Херцеговина" => "BA",
        "Barbados" => "BB",
        "বাংলাদেশ" => "BD",
        "België" => "BE",
        "Belgique" => "BE",
        "Belgien" => "BE",
        "Burkina Faso" => "BF",
        "България" => "BG",
        "البحرين" => "BH",
        "Uburundi" => "BI",
        "Burundi" => "BI",
        "Bénin" => "BJ",
        "Bermuda" => "BM",
        "Brunei Darussalam" => "BN",
        "بروني دارالسلام" => "BN",
        "Bolivia" => "BO",
        "Wuliwya" => "BO",
        "Volívia" => "BO",
        "Buliwya" => "BO",
        "Brasil" => "BR",
        "Bahamas" => "BS",
        "འབྲུག་ཡུལ།" => "BT",
        "Bouvetøya" => "BV",
        "Botswana" => "BW",
        "Беларусь" => "BY",
        "Belize" => "BZ",
        "Canada" => "CA",
        "Cocos (Keeling) Islands" => "CC",
        "République démocratique du Congo" => "CD",
        "République centrafricaine" => "CF",
        "Ködörösêse tî Bêafrîka" => "CF",
        "République du Congo" => "CG",
        "Schweiz" => "CH",
        "Suisse" => "CH",
        "Svizzera" => "CH",
        "Svizra" => "CH",
        "Côte d’Ivoire" => "CI",
        "Cook Islands" => "CK",
        "Chile" => "CL",
        "Cameroun" => "CM",
        "Cameroon" => "CM",
        "中國" => "CN",
        "中国" => "CN",
        "Colombia" => "CO",
        "Costa Rica" => "CR",
        "Cuba" => "CU",
        "Cabo Verde" => "CV",
        "Christmas Island" => "CX",
        "Κύπρος" => "CY",
        "Kıbrıs" => "CY",
        "Česko" => "CZ",
        "Deutschland" => "DE",
        "Deutſchland" => "DE",
        "جيبوتي" => "DJ",
        "Djibouti" => "DJ",
        "Danmark" => "DK",
        "Dominica" => "DM",
        "República Dominicana" => "DO",
        "الجزائر" => "DZ",
        "Ecuador" => "EC",
        "Eesti" => "EE",
        "مصر" => "EG",
        "الصحراء الغربية" => "EH",
        "ኤርትራ" => "ER",
        "إرتريا" => "ER",
        "España" => "ES",
        "ኢትዮጵያ" => "ET",
        "European Union" => "EU",
        "Европейски съюз" => "EU",
        "Evropská unie" => "EU",
        "Den Europæiske Union" => "EU",
        "Europäische Union" => "EU",
        "Europäiſche Union" => "EU",
        "Ευρωπαϊκή Ένωση" => "EU",
        "Euroopa Liit" => "EU",
        "Euroopan unioni" => "EU",
        "Union européenne" => "EU",
        "An tAontas Eorpach" => "EU",
        "An tAontas Eorpaċ" => "EU",
        "Europska unija" => "EU",
        "Európai Unió" => "EU",
        "Unione Europea" => "EU",
        "Eiropas Savienība" => "EU",
        "Europos Sąjunga" => "EU",
        "Unjoni Ewropea" => "EU",
        "Europese Unie" => "EU",
        "Unia Europejska" => "EU",
        "União Europeia" => "EU",
        "Uniunea Europeană" => "EU",
        "Európska únia" => "EU",
        "Evropska unija" => "EU",
        "Unión Europea" => "EU",
        "Europeiska unionen" => "EU",
        "Suomi" => "FI",
        "Finland" => "FI",
        "Fiji" => "FJ",
        "Viti" => "FJ",
        "Falkland Islands" => "FK",
        "Micronesia" => "FM",
        "Føroyar" => "FO",
        "Færøerne" => "FO",
        "France" => "FR",
        "Gabon" => "GA",
        "United Kingdom" => "GB",
        "Grenada" => "GD",
        "საქართველო" => "GE",
        "Guyane française" => "GF",
        "Guernsey" => "GG",
        "Dgèrnésy" => "GG",
        "Ghana" => "GH",
        "Gibraltar" => "GI",
        "Kalaallit Nunaat" => "GL",
        "Grønland" => "GL",
        "Gambia" => "GM",
        "Guinée" => "GN",
        "Guadeloupe" => "GP",
        "Guinea Ecuatorial" => "GQ",
        "Guinée équatoriale" => "GQ",
        "Guiné Equatorial" => "GQ",
        "Ελλάδα" => "GR",
        "South Georgia and the South Sandwich Islands" => "GS",
        "Guatemala" => "GT",
        "Guam" => "GU",
        "Guåhån" => "GU",
        "Guiné-Bissau" => "GW",
        "Guyana" => "GY",
        "香港" => "HK",
        "Hong Kong" => "HK",
        "Heard and McDonald Islands" => "HM",
        "Honduras" => "HN",
        "Hrvatska" => "HR",
        "Haïti" => "HT",
        "Ayiti" => "HT",
        "Magyarország" => "HU",
        "Indonesia" => "ID",
        "Éire" => "IE",
        "Ireland" => "IE",
        "ישראל" => "IL",
        "إسرائيل" => "IL",
        "Isle of Man" => "IM",
        "Ellan Vannin" => "IM",
        "India" => "IN",
        "ভাৰত" => "IN",
        "ভারত" => "IN",
        "ભારત" => "IN",
        "ಭಾರತ" => "IN",
        "भारोत" => "IN",
        "ഇന്ത്യ" => "IN",
        "ଭାରତ" => "IN",
        "ਭਾਰਤ" => "IN",
        "भारतम्" => "IN",
        "ڀارت" => "IN",
        "இந்தியா" => "IN",
        "భారత" => "IN",
        "بھارت" => "IN",
        "British Indian Ocean Territory" => "IO",
        "العراق" => "IQ",
        "ایران" => "IR",
        "Ísland" => "IS",
        "Italia" => "IT",
        "Jersey" => "JE",
        "Jèrri" => "JE",
        "Jamaica" => "JM",
        "الأردن" => "JO",
        "日本" => "JP",
        "Kenya" => "KE",
        "Кыргызстан" => "KG",
        "កម្ពុជា" => "KH",
        "Kiribati" => "KI",
        "Komori" => "KM",
        "قُمُرِ" => "KM",
        "Comores" => "KM",
        "جزر القمر" => "KM",
        "Saint Kitts and Nevis" => "KN",
        "조선" => "KP",
        "朝鮮" => "KP",
        "한국" => "KR",
        "韓國" => "KR",
        "Kosova" => "KV",
        "Косово" => "KV",
        "الكويت" => "KW",
        "Cayman Islands" => "KY",
        "Қазақстан" => "KZ",
        "ປະເທດ​ລາວ" => "LA",
        "لبنان" => "LB",
        "Saint Lucia" => "LC",
        "Liechtenstein " => "LI",
        "Liechtenſtein" => "LI",
        "ශ්‍රී ලංකාව" => "LK",
        "இலங்கை" => "LK",
        "Liberia" => "LR",
        "Lesotho" => "LS",
        "Lietuva" => "LT",
        "Luxembourg" => "LU",
        "Luxemburg" => "LU",
        "Lëtzebuerg" => "LU",
        "Latvija" => "LV",
        "ليبيا" => "LY",
        "المغرب" => "MA",
        "Monaco" => "MC",
        "Moldova" => "MD",
        "Молдова" => "MD",
        "Crna Gora" => "ME",
        "Црна Гора" => "ME",
        "Madagascar" => "MG",
        "Madagasikara" => "MG",
        "Marshall Islands" => "MH",
        "Aelōñin Ṃajeḷ" => "MH",
        "Македонија" => "MK",
        "Mali" => "ML",
        "Mẏãma" => "MM",
        "Монгол улс" => "MN",
        "ᠮᠣᠩᠭ᠋ᠣᠯ ᠤᠯᠤᠰ" => "MN",
        "澳門" => "MO",
        "澳门" => "MO",
        "Macau" => "MO",
        "Northern Mariana Islands" => "MP",
        "Martinique" => "MQ",
        "موريتانيا" => "MR",
        "Mauritanie" => "MR",
        "Montserrat" => "MS",
        "Malta" => "MT",
        "Mauritius " => "MU",
        "Maurice" => "MU",
        "ދިވެހިރާއްޖެ" => "MV",
        "Malawi" => "MW",
        "Malaŵi" => "MW",
        "México" => "MX",
        "Mēxihco" => "MX",
        "Malaysia" => "MY",
        "مليسيا" => "MY",
        "Moçambique" => "MZ",
        "Namibia" => "NA",
        "Nouvelle-Calédonie" => "NC",
        "Niger" => "NE",
        "Norfolk Island" => "NF",
        "Nigeria" => "NG",
        "Nicaragua" => "NI",
        "Nederland" => "NL",
        "Norge" => "NO",
        "Noreg" => "NO",
        "नेपाल" => "NP",
        "Nauru" => "NR",
        "Naoero" => "NR",
        "Niue" => "NU",
        "New Zealand" => "NZ",
        "Aotearoa" => "NZ",
        "عمان" => "OM",
        "Panamá" => "PA",
        "Perú" => "PE",
        "Polynésie française" => "PF",
        "Papua New Guinea" => "PG",
        "Papua Niugini" => "PG",
        "Pilipinas" => "PH",
        "Philippines" => "PH",
        "پاکستان" => "PK",
        "Polska" => "PL",
        "Saint-Pierre-et-Miquelon" => "PM",
        "Pitcairn Islands" => "PN",
        "Puerto Rico" => "PR",
        "فلسطين" => "PS",
        "Portugal" => "PT",
        "Belau" => "PW",
        "Palau" => "PW",
        "Paraguay" => "PY",
        "قطر" => "QA",
        "La Réunion" => "RE",
        "România" => "RO",
        "Србија " => "RS",
        "Srbija" => "RS",
        "Россия" => "RU",
        "Rwanda" => "RW",
        "السعودية" => "SA",
        "Solomon Islands" => "SB",
        "Seychelles" => "SC",
        "Sesel" => "SC",
        "السودان" => "SD",
        "Sverige" => "SE",
        "Singapore" => "SG",
        "新加坡" => "SG",
        "Singapura " => "SG",
        "سيڠاڤورا" => "SG",
        "சிங்கப்பூர்" => "SG",
        "Saint Helena" => "SH",
        "Slovenija" => "SI",
        "Svalbard og Jan Mayen øyene" => "SJ",
        "Svalbard og Jan Mayen øyane" => "SJ",
        "Slovensko" => "SK",
        "Sierra Leone" => "SL",
        "San Marino" => "SM",
        "Sénégal" => "SN",
        "Soomaaliya" => "SO",
        "الصومال" => "SO",
        "Suriname" => "SR",
        "South Sudan" => "SS",
        "São Tomé e Príncipe" => "ST",
        "El Salvador" => "SV",
        "سورية" => "SY",
        "eSwatini" => "SZ",
        "Swaziland" => "SZ",
        "Turks and Caicos Islands" => "TC",
        "Tchad" => "TD",
        "تشاد" => "TD",
        "Terres australes et antarctiques françaises" => "TF",
        "Togo" => "TG",
        "ประเทศไทย" => "TH",
        "Тоҷикистон" => "TJ",
        "Tokelau" => "TK",
        "Timór-Leste" => "TL",
        "Timor-Leste" => "TL",
        "Türkmenistan" => "TM",
        "Түркменистан" => "TM",
        "تونس" => "TN",
        "Tonga" => "TO",
        "Türkiye" => "TR",
        "Trinidad and Tobago" => "TT",
        "Tuvalu" => "TV",
        "臺灣" => "TW",
        "台湾" => "TW",
        "Tanzania" => "TZ",
        "Україна" => "UA",
        "Uganda" => "UG",
        "United States Minor Outlying Islands" => "UM",
        "United States of America" => "US",
        "Uruguay" => "UY",
        "Oʻzbekiston" => "UZ",
        "Ўзбекистон" => "UZ",
        "Civitas Vaticana" => "VA",
        "Saint Vincent and the Grenadines" => "VC",
        "Venezuela" => "VE",
        "British Virgin Islands" => "VG",
        "U.S. Virgin Islands" => "VI",
        "Việt Nam" => "VN",
        "Vanuatu" => "VU",
        "Wallis-et-Futuna" => "WF",
        "Samoa" => "WS",
        "Sāmoa" => "WS",
        "اليمن" => "YE",
        "Mayotte" => "YT",
        "Suid-Afrika" => "ZA",
        "South Africa" => "ZA",
        "iSewula Afrika" => "ZA",
        "Afrika-Borwa" => "ZA",
        "Afrika Borwa" => "ZA",
        "iNingizimu Afrika" => "ZA",
        "Aferika Borwa" => "ZA",
        "Afrika Dzonga" => "ZA",
        "Afurika Tshipembe" => "ZA",
        "uMzantsi Afrika" => "ZA",
        "Zambia" => "ZM",
        "Zimbabwe" => "ZW",
    ];

    /**
     * Get country code
     *
     * @param string $country
     * @return string
     */
    protected static function countryCode($country)
    {
        $country = (string)$country;
        if (strlen($country) != 2) $country = Countries::getCode($country);

        return $country;
    }

    /**
     * Get list of native names
     *
     * @return array
     */
    public static function getList()
    {
        return array_flip(array_unique(static::$list));
    }

    /**
     * Get country native name/names
     *
     * @param string $country
     * @return string
     */
    public static function getName($country)
    {
        return implode(", ", array_keys(static::$list, static::countryCode($country))) ? : null;
    }

    /**
     * Get only one first country native name
     *
     * @param string $country
     * @return string
     */
    public static function getOneName($country)
    {
        return array_search(static::countryCode($country), static::$list) ? : null;
    }

}


